name: YouTube Trending Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs daily at midnight UTC

jobs:
  fetch_trending:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pandas requests matplotlib seaborn

      - name: Fetch Trending Videos
        run: python fetch_trending.py

      - name: Commit Trending Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add trending_videos.csv
          git commit -m "Update trending videos data"
          git push

  analyze_trends:
    needs: fetch_trending
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pandas matplotlib seaborn

      - name: Analyze Trends
        run: python analyze_trends.py
